[build]
builder = "NIXPACKS"
buildCommand = "cd packages/client && npm install && npm run build && cd ../server && bun install"

[deploy]
startCommand = "cd packages/server && bun run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"