[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd packages/server && bun run prisma generate && bun run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"