[build]
builder = "NIXPACKS"
buildCommand = "bun install && cd packages/client && bun install && bun run build && cd ../server && bun install"

[deploy]
startCommand = "bun run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
NODE_VERSION = "22"