[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "bun install && cd packages/client && bun install && bun run build && cd ../server && bun install"

[deploy]
startCommand = "bun run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NODE_VERSION = "22"
PORT = "3000"